### ISSUE TITLE
OOM了啊老哥 

### ISSUE THREAD

**Issue by fulisadawang** [QDqiaodong/Reader#1]

**Comment by fulisadawang** [comment]
10-30 13:17:22.259 com.github.reader E/dalvikvm-heap: Out of memory on a 10543120-byte allocation.
10-30 13:17:22.269 com.github.reader W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x416ebba8)
10-30 13:17:22.269 com.github.reader E/AndroidRuntime: FATAL EXCEPTION: main
                                                       Process: com.github.reader, PID: 6119
                                                       java.lang.OutOfMemoryError
                                                           at android.graphics.Bitmap.nativeCreate(Native Method)
                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:786)
                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:753)
                                                           at com.github.reader.app.ui.view.BasePageView.drawBg4Bitmap(BasePageView.java:344)
                                                           at com.github.reader.app.ui.view.BasePageView.setPage(BasePageView.java:201)
                                                           at com.github.reader.pdf.ui.view.PDFPageView.setPage(PDFPageView.java:126)
                                                           at com.github.reader.pdf.ui.adapater.MuPDFPageAdapter$1.onPostExecute(MuPDFPageAdapter.java:85)
                                                           at com.github.reader.pdf.ui.adapater.MuPDFPageAdapter$1.onPostExecute(MuPDFPageAdapter.java:70)
                                                           at com.github.reader.pdf.model.AsyncTask.finish(AsyncTask.java:634)
                                                           at com.github.reader.pdf.model.AsyncTask.access$600(AsyncTask.java:180)
                                                           at com.github.reader.pdf.model.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:647)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:136)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                           at dalvik.system.NativeStart.main(Native Method)
10-30 13:17:22.349 ? W/ActivityManager:   Force finishing activity com.github.reader/.pdf.ui.activity.PdfActivity
                                          Force finishing activity com.github.reader/.app.ui.acitivity.ChoosePDFActivity
10-30 13:17:22.359 ? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1123 android.content.ContextWrapper.sendBroadcast:365 android.app.Dialog.show:253 com.android.server.am.ActivityManagerService$2.handleMessage:1124 android.os.Handler.dispatchMessage:102 
10-30 13:17:22.859 ? W/ActivityManager: Activity pause timeout for ActivityRecord{41e08c30 u0 com.github.reader/.pdf.ui.activity.PdfActivity t461 f}
